kind = "web"
previewPath = "/"
title = "We Take Your Job"
version = "1.0.0"
id = "artifacts/wetakeyourjob"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26169

[services.development]
run = "pnpm --filter @workspace/unboks-public-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/unboks-public-website", "run", "build" ]
publicDir = "artifacts/wetakeyourjob/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26169"
BASE_PATH = "/"
