server {
    server_name unboks.org www.unboks.org;

    root /var/www/unboks-public/current;
    index index.html;

    access_log /var/log/nginx/unboks-public.access.log;
    error_log /var/log/nginx/unboks-public.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|webp|svg|ico|woff2?)$ {
        try_files $uri =404;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
